### PR TITLE
13 scheduler start topology

### PR DESCRIPTION
**Pull request by 01oseluiz**
Captura de tela de 2019-05-13 23-11-36

### CODE REVIEW

**Comment by AndreLaranjeira** [comment]
I see two small problems:
1) It seems your fork_nodes() function only creates the last node... repeatedly. Maybe update the position of the nodes array used in the execvp function call to somehow use the iterator instead of a constant.
2) Shouldn't we be using execl instead of execvp?

**Comment by 01oseluiz** [comment]
> I see two small problems:
> 
>     1. It seems your fork_nodes() function only creates the last node... repeatedly. Maybe update the position of the nodes array used in the execvp function call to somehow use the iterator instead of a constant.
> 
>     2. Shouldn't we be using execl instead of execvp?

1. I really did miss! Changing from dynamic mode to static i forgot to change the iterator index. I think now is all correct, as showing at the image image


 
2.
- int execl(const char *path, const char *arg, ...);
This means that i have to pass all the arguments one by one as parameters.
- int execvp(const char *file, char *const argv[]);
This means that I can pass all the arguments as a array of strings, so it can be changed dynamically, and pass the file instead of path

**Comment by AndreLaranjeira** [comment]
When I execute the program I get this:

PID TTY          TIME CMD
9597 pts/1    00:00:00 bash
10653 pts/1    00:00:00 ps
21802 pts/1    00:00:00 scheduler
21803 pts/1    00:00:00 scheduler
21804 pts/1    00:00:00 scheduler
21805 pts/1    00:00:00 scheduler
21806 pts/1    00:00:00 scheduler
21807 pts/1    00:00:00 scheduler
21808 pts/1    00:00:00 scheduler
21809 pts/1    00:00:00 scheduler
21810 pts/1    00:00:00 scheduler
21811 pts/1    00:00:00 scheduler
21812 pts/1    00:00:00 scheduler
21813 pts/1    00:00:00 scheduler
21814 pts/1    00:00:00 scheduler
21815 pts/1    00:00:00 scheduler
21816 pts/1    00:00:00 scheduler
21817 pts/1    00:00:00 scheduler
21818 pts/1    00:00:00 scheduler
21819 pts/1    00:00:00 scheduler
21820 pts/1    00:00:00 scheduler
21821 pts/1    00:00:00 scheduler
21822 pts/1    00:00:00 scheduler
21823 pts/1    00:00:00 scheduler
21824 pts/1    00:00:00 scheduler
21825 pts/1    00:00:00 scheduler

It seems you have overloaded my process count, because if the exec function call fails, there is no handling... Please fix this and, while you are at it, feel free to shorten all the macros in the config file (Nid is fine by me) and use them in your code.

**Comment by AndreLaranjeira** [comment]
Had to commit some changes and resolve merge conflicts... Please make sure to resolve as many merge conflicts as you can **before** submitting the PR.

**Pull request merged**
