### PR TITLE
Develop

### PR DESCRIPTION
**Pull request by Hugo-NF**

### CODE REVIEW

**Comment by Hugo-NF** [comment]
Everything looks good, we just have to remove the Andre's flag implementation to scheduler panic shutdown.

**Review by AndreLaranjeira — CHANGES_REQUESTED** [review]
Things seem to be working fine. I did find some small problems, though, and have created a branch 'patch_sprint_02'. If somebody could take a look at that really quickly and merge it into the develop branch, I would very much appreciate it.

**Comment by AndreLaranjeira** [comment]
> Everything looks good, we just have to remove the Andre's flag implementation to scheduler panic shutdown.

I tried reverting to the original implementation, but that generated some problems related to process deletion in my computer.

**Review by AndreLaranjeira — APPROVED** [review]
Now everything looks good!

**Review by 01oseluiz — APPROVED** [review]

**Review by victoragcosta — APPROVED** [review]
Pretty good, the gut that made the last commits seems pretty good at that.

**Pull request merged**
